config/routes.rb
Rails.application.routes.draw do

  root 'pins#all', page: 'home'
  

  resources :users

  resources :boards, shallow: true do
    resources :pins
  end

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  get '/pages/:page', to: 'pages#show'

end

app/models/board.rb
class Board < ActiveRecord::Base
	belongs_to :user

	has_many :pins, dependent: :destroy

	has_attached_file :image, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	before_validation { image.clear if @delete_image }

	 def delete_image
	   @delete_image ||= false
	 end

	 def delete_image=(value)
	   @delete_image  = !value.to_i.zero?
	 end
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :board

  has_attached_file :image, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :email, presence: true, uniqueness: true
 

	has_many :boards, dependent: :destroy

	has_attached_file :image, styles: { medium: "500x500>", thumb: "250x250>" }, presence: true
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	before_validation { image.clear if @delete_image }

	 def delete_image
	   @delete_image ||= false
	 end

	 def delete_image=(value)
	   @delete_image  = !value.to_i.zero?
	 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  config.relative_url_root = ""

  private
  	helper_method :current_user

  def current_user
  	@current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end  	

  def authorize
  	redirect_to login_path, alert: 'Not authorized - you must be logged in!' if current_user.nil?
  end  
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
	before_action :set_board, only: [:show, :edit, :update, :destroy]
	before_action :authorize, except: [:index, :show]

	def index
		@boards = Board.all
		@user = current_user
	end

	def show
		@board = Board.find(params[:id])
	end

	def new
		@board = Board.new
	end

	def edit
	end

	def create
		@board = Board.new(board_params)
		@board.user = current_user
		if @board.save
			redirect_to boards_path
		else
			render :new
		end
	end

	def update
		if @board.update_attributes(board_params)
			redirect_to boards_path
		else
			render :edit
		end
	end

	def destroy
		@board.destroy
		redirect_to boards_path
	end

	private
		def set_board
			@board = Board.find(params[:id])
		end

		def board_params
			params.require(:board).permit(:name, :image)
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def show
	    page = params[:page]
	    render "pages/#{page}"
	end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :set_pin, only: [:show, :edit, :update, :destroy]
	before_action :authorize, except: [:index, :show]

	def new
		@pin = Pin.new
		@board = Board.find(params[:board_id])
	end

	def edit
	end

	def create
		@board = Board.find(params[:board_id])
		@pin = Pin.new(pin_params)
		@pin.board = @board
		if @pin.save
			redirect_to @board
		else
			render :new
		end
	end

	def update
		if @pin.update_attributes(pin_params)
			redirect_to board_path(@pin.board)
		else
			render :edit
		end
	end

	def destroy
		@pin.destroy
		redirect_to :back
	end

	def all
		@pins = Pin.all
		@user = current_user	
	end

	private

	def set_pin
		@pin = Pin.find(params[:id])
	end

	def pin_params
		params.require(:pin).permit(:description, :image)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id 
			redirect_to user_path(:id), notice: 'Logged in!'
		else
			flash.now.alert = 'Invalid login credentials - try again!'
			render :new
		end
	end

	def destroy
		name = current_user.name
		session[:user_id] = nil
		redirect_to root_path, notice: "Logged out! - Come back again #{name}!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have successfully signed up!" 
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    @user = current_user
    
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      redirect_to user_path(:id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :about, :location)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.erb
<%= form_for @board, html: { multipart: true } do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <% if @board.image.exists? %>
    <%= image_tag @board.image.url(:thumb) %><br/>
    <%= f.check_box :delete_image %>Delete Image<br/>
  <% end %>
  <div>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Edit Board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<div class="flex-container">
  <div class="new-board-button"><%= link_to image_tag("new-board-button.png"), new_board_path %></div>
  <div class="headingName"><%= current_user.name %><br>
    <%= current_user.location %>&nbsp; &frasl; &nbsp;<%= current_user.about %>
  </div>  
  <div class="profile-image">
    <%= image_tag current_user.image.url, class:'img-responsive rounded image-cropper' %>
    <%= link_to 'Edit Profile', edit_user_path(current_user), :class => 'btn btn-xs btn-default edit' %>
  </div>
</div>

<ul class="nav nav-pills">
  <li class="active"><%= link_to "Boards", boards_path %></li>
  <li><%= link_to "Pins" %></li>
</ul>

<% current_user.boards.each do |board| %>
  <div class="board col-md-3">
    
    <div class="board-image">
      <%= image_tag board.image.url(:medium) %>
    </div>
    
    <div class="board-block">
      <p class="board-text boardLabel"><%= link_to board.name, board %></p>
      <p class="pin-count"><%= board.pins.count %> Pins</p>
        <% if board.user == current_user %>
          <%= link_to 'Edit', edit_board_path(board), :class => 'btn btn-xs btn-default edit' %>  
          <%= link_to 'Delete', board, :class => 'btn btn-xs btn-default delete', method: :delete, data: {
            confirm: 'Are you sure?' } %> 
        <% end %> 
    </div>
  
  </div>
<% end %>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form' %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %> |
<%= link_to 'New Pin', new_board_pin_path(@board) %>

<div class="boardHeader">
  <h1 class="boardName"><%= @board.name %></h1>
  <%= @board.pins.count %> Pins
</div>

<div class="container">
  <% @board.pins.each do |pin| %>
  
    <div class="pin">
      <%= image_tag pin.image.url, :class => "pin-img-top" %>
        <% if @board.user == current_user %>
            <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn btn-xs btn-default edit' %>
            <%= link_to 'Delete', pin, :class => 'btn btn-xs btn-default delete', method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
      <div class="pin-block">
        <h4 class="pin-title"><%= pin.description %></h4>
        <p class="pin-text"></p>
      </div>
    </div>
  
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Pinterest Project</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>

<body>

  <nav class="navbar">
    <div class="container-fluid">
      <ul class="nav navbar-nav">
        <li><%= link_to(image_tag("pinterest-logo.png"), root_path) %></li>
        <div class="navbar-left">
        <% if current_user %>
          Welcome, <%= current_user.name %>
          &nbsp;|&nbsp;
          <%= link_to 'Log Out', session_path('dummy'), method: :delete %>
        <% else %>
          <%= link_to 'Log In', login_path %>
          &nbsp;&nbsp;|&nbsp;&nbsp;
          <%= link_to 'Sign Up', new_user_path %>
        <% end %>
        </div>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to(image_tag("user-avatar.png"), user_path(:id)) %></li>
      </ul>
    </div>
  </nav>

  <div class="container-fluid" id="container"> 
  <%= yield %>
  </div>

</body>

</html>

app/views/pins/all.html.erb
<div class="container">
	<% @pins.each do |pin| %>
	  <div class="pin">
	    <%= image_tag pin.image.url, :class => "pin-img-top" %>
	    	<% if pin.board.user == current_user %>
	        	<%= link_to 'Edit', edit_pin_path(pin), :class => 'btn btn-xs btn-default edit' %>
	        	<%= link_to 'Delete', pin, :class => 'btn btn-xs btn-default delete', method: :delete, data: { confirm: 'Are you sure?' } %>
	      	<% end %>
	    <div class="pin-block">
	      <h4 class="pin-title"><%= pin.description %></h4>
	      <p class="pin-text"></p>
	    </div>
	  </div>
	<% end %>
</div>

app/views/pins/edit.html.erb
<h1>Edit Pin</h1>
<%= form_for @pin, html: { multipart: true } do |form| %>

  <%= form.label :description %>
  <%= form.text_field :description %><br>
  
  <%= form.submit 'Save Pin!' %>

<% end %>

<%= link_to 'Back', board_path(@pin.board) %>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= form_for [@board, @pin], html: { multipart: true } do |form| %>

  <%= form.label :description %>
  <%= form.text_field :description %><br>

  <%= form.file_field :image %><br><br>
	
  <%= form.submit 'Save Pin!' %>

<% end %>

<%= link_to 'Back', boards_path %>

app/views/users/edit.html.erb
<%= form_for @user, html: { multipart: true } do |f| %>

	<% if @user.image.exists? %>
	  <%= image_tag @user.image.url(:thumb) %><br/>
	  <%= f.check_box :delete_image %>Delete Image<br/>
	<% end %>

	<% f.label :name %><br>
	<%= f.text_field :name %><br>

	<%= f.label :about %><br>
	<%= f.text_field :about %><br>

	<%= f.label :location %><br>
	<%= f.text_field :location %><br>
	
	<%= f.file_field :image %>

	<div class="actions"><%= f.submit %></div>
	
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= bootstrap_form_for @user, html: { multipart: true } do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <% f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <% f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <% f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <% f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
  <%= f.file_field :image %><br><br>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

app/views/users/show.html.erb
<div class="flex-container">
  <div class="headingName"><%= current_user.name %><br>
    <%= current_user.location %>&nbsp; &frasl; &nbsp;<%= current_user.about %>
  </div>  
  <div class="profile-image">
    <%= image_tag current_user.image.url, class:'img-responsive rounded image-cropper' %>
    <%= link_to 'Edit Profile', edit_user_path(current_user), :class => 'btn btn-xs btn-default edit' %>
  </div>
</div>

<ul class="nav nav-pills">
  <li class="active"><%= link_to "Boards", boards_path %></li>
  <li><%= link_to "Pins" %></li>
</ul>

<% current_user.boards.each do |board| %>
  <div class="board col-md-3">
    
    <div class="board-image">
      <%= image_tag board.image.url(:medium) %>
    </div>
    
    <div class="board-block">
      <p class="board-text boardLabel"><%= link_to board.name, board %></p>
      <p class="pin-count"><%= board.pins.count %> Pins</p>
        <% if board.user == current_user %>
          <%= link_to 'Edit', edit_board_path(board), :class => 'btn btn-xs btn-default edit' %>  
          <%= link_to 'Delete', board, :class => 'btn btn-xs btn-default delete', method: :delete, data: {
            confirm: 'Are you sure?' } %> 
        <% end %> 
    </div>
  
  </div>
<% end %>